### ISSUE TITLE
bro mau nanya

### ISSUE THREAD

**Issue by aryob** [rpnjul/ujian-online#2]
ini kenapa ya pas mau login selalu checking terus, ga masuk2 , salah dimana ya? 
terimakasih sebelumnya
https://imgur.com/DYudljp

**Comment by aryob** [comment]
http://pi.aryob.me/

seperti ini bro

**Comment by rpnjul** [comment]
kalo saya liat dari respon ajax loginnya 404, yang berarti url /auth/cek_login ga ada, coba di cek dulu route nya atau mungkin ada file yang kurang
